Repository edualgo/Grokking-Machine-Learning, pull requests merged in 2021-02, with the labels that each got.

#74 Added ID3 Algorithm for Decision Tree Classifier
  Notebooks/ID3 Algorithm/ID3.ipynb
  Notebooks/ID3 Algorithm/README.md
  Notebooks/ID3 Algorithm/tennis.csv
Labels: DWOC, Level-5, enhancement

#78 Hidden markov chains #68
  Rap generator/Rap_Lyric_Generator-master/MarkovRap.py
  Rap generator/Rap_Lyric_Generator-master/README.md
  Rap generator/Rap_Lyric_Generator-master/lyrics1.txt
  Rap generator/Rap_Lyric_Generator-master/lyrics2.txt
Labels: DWOC, Level-5

#81 UrbanSound8K
  Notebooks/UrbanSound8K/README.md
  Notebooks/UrbanSound8K/UrbanSound8K.ipynb
  Notebooks/UrbanSound8K/Urbansound.png
  Notebooks/UrbanSound8K/best_model.hdf5
Labels: DWOC, Level-4, enhancement

#82 Natural Language Processing on Disaster tweets
  Notebooks/NLP_With_Disaster_tweets/.ipynb_checkpoints/nlp-with-disaster-tweets -checkpoint.ipynb
  Notebooks/NLP_With_Disaster_tweets/Readme.md
  Notebooks/NLP_With_Disaster_tweets/nlp-with-disaster-tweets .ipynb
  Notebooks/NLP_With_Disaster_tweets/test.csv
  Notebooks/NLP_With_Disaster_tweets/train.csv
Labels: DWOC, Level-3, enhancement

#92 Added Parkinsons Prediction Notebook
  Notebooks/Perkinson's Disease Prediction/Perkinsons_Prediction.ipynb
  Notebooks/Perkinson's Disease Prediction/README.md
Labels: DWOC, Level-4, enhancement

#95 Voice-based gender recognition
  Notebooks/Voice-Gender identification/Gender_Voice.ipynb
  Notebooks/Voice-Gender identification/Outputs/Models.png
  Notebooks/Voice-Gender identification/Outputs/dnn_model.PNG
  Notebooks/Voice-Gender identification/Outputs/genderVoice.png
  Notebooks/Voice-Gender identification/README.md
Labels: DWOC, Level-5, enhancement

#101 Wine classification
  Notebooks/Wine_Classification/Wine_Classification.ipynb
  Notebooks/Wine_Classification/winequality-red.csv
Labels: DWOC, Level-3, enhancement

#103 Added Casava Plant Disease Prediction Notebook
  Notebooks/Casava Plant Disease Prediction/Cassava_Plant_Disease.ipynb
  Notebooks/Casava Plant Disease Prediction/README.md
Labels: DWOC, Level-5, enhancement

#116 Logistic Regression
  Notebooks/Logistic_Regression/logistic_Regression.ipynb
Labels: DWOC, Level-5, enhancement

#119 Rohit bisht rise patch 2
  Notebooks/Text-Summarization/README.md
  Notebooks/Text-Summarization/empty_file.txt
  Notebooks/Text-Summarization/file.txt
  Notebooks/Text-Summarization/images/help.png
  Notebooks/Text-Summarization/images/inputfile.png
  Notebooks/Text-Summarization/images/run.png
  Notebooks/Text-Summarization/images/rundefault.png
  Notebooks/Text-Summarization/images/samefile.png
  Notebooks/Text-Summarization/summarize.py
  Text-Summarization/README.txt
  Text-Summarization/empty_file.txt
  Text-Summarization/file.txt
  Text-Summarization/images/help.png
  Text-Summarization/images/inputfile.png
  Text-Summarization/images/run.png
  Text-Summarization/images/rundefault.png
  Text-Summarization/images/samefile.png
  Text-Summarization/summarize.py
Labels: DWOC, Level-5, enhancement

#120 Added Fake News Detection using LSTM
  Notebooks/Fake News Detection using LSTM/Fake_News_detector_using_LSTM.ipynb
  Notebooks/Fake News Detection using LSTM/README.md
  Notebooks/Fake News Detection using LSTM/classification.png
Labels: DWOC, Level-4, enhancement

#122 Movie Recommendation website
  Notebooks/Movie_Recommendation_Website/Procfile
  Notebooks/Movie_Recommendation_Website/README.md
  Notebooks/Movie_Recommendation_Website/datasets/data.csv
  Notebooks/Movie_Recommendation_Website/datasets/final_data.csv
  Notebooks/Movie_Recommendation_Website/datasets/main_data.csv
  Notebooks/Movie_Recommendation_Website/datasets/movie_metadata.csv
  Notebooks/Movie_Recommendation_Website/datasets/new_data.csv
  Notebooks/Movie_Recommendation_Website/datasets/reviews.txt
  Notebooks/Movie_Recommendation_Website/main.py
  Notebooks/Movie_Recommendation_Website/main_data.csv
  Notebooks/Movie_Recommendation_Website/nlp_model.pkl
  Notebooks/Movie_Recommendation_Website/preprocessing 1.ipynb
  Notebooks/Movie_Recommendation_Website/preprocessing 2.ipynb
  Notebooks/Movie_Recommendation_Website/preprocessing 3.ipynb
  Notebooks/Movie_Recommendation_Website/preprocessing_4.ipynb
  Notebooks/Movie_Recommendation_Website/sentiment.ipynb
  Notebooks/Movie_Recommendation_Website/static/autocomplete.js
  Notebooks/Movie_Recommendation_Website/static/image.jpg
  Notebooks/Movie_Recommendation_Website/static/loader.gif
  Notebooks/Movie_Recommendation_Website/static/recommend.js
  Notebooks/Movie_Recommendation_Website/static/style.css
  Notebooks/Movie_Recommendation_Website/templates/home.html
  Notebooks/Movie_Recommendation_Website/templates/recommend.html
  Notebooks/Movie_Recommendation_Website/tranform.pkl
Labels: DWOC, Level-5, enhancement

#124 Stock Sentiment Analysis
  Notebooks/Stock Sentiment Analysis/Readme.md
  Notebooks/Stock Sentiment Analysis/Stock_Sentiment_Analysis.ipynb
Labels: DWOC, Level-5, enhancement

#126 Heart disease prediction using 7 ML algorithms
  Apple Stock Prediction/EOD-AAPL.csv
  Apple Stock Prediction/readme.md
  Apple Stock Prediction/stocks_aapl.ipynb
  heart disease prediction/Heart_disease_prediction.ipynb
  heart disease prediction/README.md
  heart disease prediction/heart.csv
Labels: DWOC, Level-5, enhancement

#131 Added Image Segmentation using UNet
  Notebooks/Image Segmentation using UNet/Image_Segmentation.ipynb
  Notebooks/Image Segmentation using UNet/README.md
  Notebooks/Image Segmentation using UNet/image.png
  Notebooks/Image Segmentation using UNet/segment.png
Labels: DWOC, Level-5, enhancement

#138 Text-generator
  Text_generator/frankenstein.txt
  Text_generator/text_generation_project.ipynb
Labels: DWOC, Level-4, enhancement

#139 Cryptocurrency Data Analysis and Visualization PR
  Notebooks/Cryptocurrency Data Analysis and Visualization/coinmarketcap_06122017.csv
  Notebooks/Cryptocurrency Data Analysis and Visualization/notebook1_bitcoin.ipynb
  Notebooks/Cryptocurrency Data Analysis and Visualization/readme.md
Labels: DWOC, Level-4, enhancement

#141 Cuisine Prediction using Sklearn PR
  Notebooks/Cuisine-Prediction/README.md
  Notebooks/Cuisine-Prediction/sushi1.ipynb
Labels: DWOC, Level-2, enhancement

#143 Handwritten letter and digit prediction
  Notebooks/Handwritten letter and digit prediction/Handwritten_Letter.ipynb
  Notebooks/Handwritten letter and digit prediction/Readme.md
  Notebooks/Voice emotion recognition/Readme.md
  Notebooks/Voice emotion recognition/Voice_Sentiment_Recognition.ipynb
Labels: DWOC, Level-3, enhancement

#144 Weather_analysis
  Notebooks/Text_generator/frankenstein.txt
  Notebooks/Text_generator/text_generation_project.ipynb
  Notebooks/Weather_analyse/Weather_Analyser.ipynb
  Notebooks/Weather_analyse/Weather_Data.csv
Labels: DWOC, Level-4, enhancement

#145 Sentimental-Analysis
  Notebooks/Sentimental-Analysis/README.md
  Notebooks/Sentimental-Analysis/Sentimental.ipynb
  Notebooks/Sentimental-Analysis/emotions.txt
  Notebooks/Sentimental-Analysis/read.txt
  Notebooks/Sentimental-Analysis/sentimentGraph.png
  Notebooks/Sentimental-Analysis/sentimental.py
Labels: DWOC, Level-4, enhancement

#146 Added Comparision of cosmetics by ingredients folder
  Notebooks/Cosmetics Comparison by ingredients/cosmetics.csv
  Notebooks/Cosmetics Comparison by ingredients/notebook.ipynb
  Notebooks/Cosmetics Comparison by ingredients/readme.md
Labels: DWOC, Level-5, enhancement

#149 Added CAPTCHA Recognition
  Notebooks/CAPTCHA Recognition/CAPTCHA_Recognition.ipynb
  Notebooks/CAPTCHA Recognition/README.md
Labels: DWOC, Level-4, enhancement

#152 Added Landmark Detection using R-CNN
  Notebooks/Landmark Detection/Landmark_Recognition.ipynb
  Notebooks/Landmark Detection/README.md
Labels: DWOC, Level-5, enhancement

#154 Reducing Traffic Mortality in USA PR
  Notebooks/Traffic mortality in USA/miles-driven.csv
  Notebooks/Traffic mortality in USA/readme.md
  Notebooks/Traffic mortality in USA/road-accidents.csv
  Notebooks/Traffic mortality in USA/traffic_mortality.ipynb
Labels: DWOC, Level-4, enhancement

#155 Added MIND Analysis and Classification
  Notebooks/MIND Data Analysis and Classification/MIND_Analysis_and_Classification.ipynb
  Notebooks/MIND Data Analysis and Classification/README.md
Labels: DWOC, Level-4, enhancement

#158 Student Data
  Notebooks/Student Data/Student_Marks_Predictor.pkl
  Notebooks/Student Data/Student_dataset.ipynb
  Notebooks/Student Data/student_info.csv
Labels: DWOC, Level-3, enhancement

#159 Uber Data Analysis
  Notebooks/Uber Data Analysis/Readme.md
  Notebooks/Uber Data Analysis/Uber_data_Visualization.ipynb
Labels: DWOC, Level-2, enhancement

#161 Blood donor prediction
  Notebooks/Blood donors prediction/README.md
  Notebooks/Blood donors prediction/notebook.ipynb
  Notebooks/Blood donors prediction/transfusion.data
Labels: DWOC, Level-3, enhancement
